# Generated by Django 4.1.1 on 2022-09-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
